name: App Deploy
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: App Build
    steps:
    - uses: actions/checkout@v1
    - id: Build-Vue
      uses: eoussama/vue-pages-action@0.0.2
      with:
        usepnpm: true
        username: 'nakamaorg'
        reponame: 'langkama-online'
        token: ${{ secrets.GITHUB_TOKEN }}
