name: App Deploy
on:
  push:
    branches:
      - main

env:
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Enabeling pnpm
      run: |
        ./scripts/env.sh
        corepack enable
        pnpm install

    - id: Build-Vue
      uses: eoussama/vue-pages-action@0.0.2
      with:
        usepnpm: true
        username: 'nakamaorg'
        reponame: 'langkama-online'
        token: ${{ secrets.GITHUB_TOKEN }}
