name: App Deploy
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: App Build
    steps:
    - uses: actions/checkout@v4
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'nakamaorg'
        reponame: 'langkama-online'
        token: ${{ secrets.GITHUB_TOKEN }}
